name = "Create: Kitchen"
author = "Daedmon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28227f67ab0e7acccff7ef2333ba63f975d1513aa4ea4a5ed74e14be0363fd8d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
