name = "Create: Kitchen"
author = "Daedmon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edcfa7468cbdb2f8e76f57b657228db18fe24e5d0fb525620150992008c2836e"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
