name = "Create: Kitchen"
author = "Daedmon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08044c6ff544c84f6419ac46cfa387f9e1f85eaf3d994b6ab96083cddcdaaef6"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
